using System.Runtime.InteropServices;
using Windows.Win32;
using Windows.Win32.Foundation;
using Windows.Win32.NetworkManagement.WindowsFilteringPlatform;

namespace EVBlocker.Core.Firewall;

/// <summary>
/// <see cref="IBootGuard"/> over the Windows Filtering Platform management API.
/// </summary>
/// <remarks>
/// WFP rather than the firewall COM API because firewall rules cannot create boot-time filters -
/// Microsoft documents that restriction outright. This is the one feature that needs to go below
/// the firewall. The interop is generated by CsWin32, for the same reason as the COM interop:
/// these structs are unions of pointers, and a hand-written layout that is one field off would
/// only show itself on an elevated machine.
///
/// Every change runs in a transaction, so a failure part-way leaves the previous state rather
/// than half a guard. Order within a transaction does not matter to the result, but the release
/// is still added before the block: if the engine ever applied them one at a time, the machine
/// would never see a moment with the block alone.
/// </remarks>
public sealed class BootGuard : IBootGuard
{
    private const string ProviderName = "EVBlocker";

    private const string Description =
        "Chặn kết nối ra ngoài lúc khởi động, tới khi Windows Firewall áp xong chính sách. Gỡ: EVBlocker.exe --remove-boot-guard";

    private const uint ErrorAccessDenied = 5;

    private const uint EAccessDenied = 0x80070005;

    public BootGuardState GetState()
    {
        using SafeHandle engine = OpenEngine();

        int guard = BootGuardFilters.Guard.Count(spec => FilterExists(engine, spec.Key));
        int release = BootGuardFilters.Release.Count(spec => FilterExists(engine, spec.Key));

        return (guard, release) switch
        {
            (0, 0) => BootGuardState.Absent,
            _ when guard == BootGuardFilters.Guard.Count && release == BootGuardFilters.Release.Count => BootGuardState.Released,
            _ when guard == BootGuardFilters.Guard.Count && release == 0 => BootGuardState.Engaged,
            _ => BootGuardState.Partial,
        };
    }

    public void Install() => InTransaction("install the boot guard", engine =>
    {
        AddProvider(engine);
        AddSubLayer(engine);

        foreach (GuardFilterSpec spec in BootGuardFilters.Release.Concat(BootGuardFilters.Guard))
        {
            AddFilterIfMissing(engine, spec);
        }
    });

    public void Release() => InTransaction("release the boot guard", engine =>
    {
        foreach (GuardFilterSpec spec in BootGuardFilters.Release)
        {
            AddFilterIfMissing(engine, spec);
        }
    });

    public void Engage() => InTransaction("engage the boot guard", engine =>
    {
        foreach (GuardFilterSpec spec in BootGuardFilters.Release)
        {
            DeleteFilter(engine, spec.Key);
        }
    });

    public void Remove() => InTransaction("remove the boot guard", engine =>
    {
        // Guard before release: removing the release first would engage the block for the rest
        // of the transaction, and although the commit is atomic there is no reason to rely on it.
        foreach (GuardFilterSpec spec in BootGuardFilters.Guard.Concat(BootGuardFilters.Release))
        {
            DeleteFilter(engine, spec.Key);
        }

        Guid subLayer = BootGuardFilters.SubLayerKey;
        IgnoreNotFound(PInvoke.FwpmSubLayerDeleteByKey0(engine, in subLayer), HRESULT.FWP_E_SUBLAYER_NOT_FOUND, "delete sublayer");

        Guid provider = BootGuardFilters.ProviderKey;
        IgnoreNotFound(PInvoke.FwpmProviderDeleteByKey0(engine, in provider), HRESULT.FWP_E_PROVIDER_NOT_FOUND, "delete provider");
    });

    private static SafeHandle OpenEngine()
    {
        // No session flags: a dynamic session would take every object it added away with it when
        // the handle closes, which is the opposite of what the release is for.
        Check(
            PInvoke.FwpmEngineOpen0(unchecked((uint)PInvoke.RPC_C_AUTHN_DEFAULT), null, null, out FwpmEngineClose0SafeHandle engine),
            "open the filtering engine");

        return engine;
    }

    private static void InTransaction(string operation, Action<SafeHandle> body)
    {
        using SafeHandle engine = OpenEngine();

        Check(PInvoke.FwpmTransactionBegin0(engine, 0), $"{operation} (begin transaction)");

        try
        {
            body(engine);
            Check(PInvoke.FwpmTransactionCommit0(engine), $"{operation} (commit)");
        }
        catch
        {
            _ = PInvoke.FwpmTransactionAbort0(engine);
            throw;
        }
    }

    private static unsafe void AddProvider(SafeHandle engine)
    {
        fixed (char* name = ProviderName)
        fixed (char* description = Description)
        {
            var provider = new FWPM_PROVIDER0
            {
                providerKey = BootGuardFilters.ProviderKey,
                displayData = new FWPM_DISPLAY_DATA0 { name = name, description = description },
                flags = PInvoke.FWPM_PROVIDER_FLAG_PERSISTENT,
            };

            IgnoreAlreadyExists(PInvoke.FwpmProviderAdd0(engine, in provider, default), "add provider");
        }
    }

    private static unsafe void AddSubLayer(SafeHandle engine)
    {
        Guid providerKey = BootGuardFilters.ProviderKey;

        fixed (char* name = "EVBlocker boot guard")
        fixed (char* description = Description)
        {
            var subLayer = new FWPM_SUBLAYER0
            {
                subLayerKey = BootGuardFilters.SubLayerKey,
                displayData = new FWPM_DISPLAY_DATA0 { name = name, description = description },
                flags = PInvoke.FWPM_SUBLAYER_FLAG_PERSISTENT,
                providerKey = &providerKey,
                weight = BootGuardFilters.SubLayerWeight,
            };

            IgnoreAlreadyExists(PInvoke.FwpmSubLayerAdd0(engine, in subLayer, default), "add sublayer");
        }
    }

    private static unsafe void AddFilterIfMissing(SafeHandle engine, GuardFilterSpec spec)
    {
        if (FilterExists(engine, spec.Key))
        {
            return;
        }

        Guid providerKey = BootGuardFilters.ProviderKey;
        FWPM_FILTER_CONDITION0* conditions = stackalloc FWPM_FILTER_CONDITION0[2];
        uint count = WriteConditions(spec, conditions);

        fixed (char* name = spec.Name)
        fixed (char* description = Description)
        {
            var filter = new FWPM_FILTER0
            {
                filterKey = spec.Key,
                displayData = new FWPM_DISPLAY_DATA0 { name = name, description = description },
                flags = spec.Lifetime switch
                {
                    GuardFilterLifetime.BootTime => FWPM_FILTER_FLAGS.FWPM_FILTER_FLAG_BOOTTIME,
                    GuardFilterLifetime.Persistent => FWPM_FILTER_FLAGS.FWPM_FILTER_FLAG_PERSISTENT,
                    _ => FWPM_FILTER_FLAGS.FWPM_FILTER_FLAG_NONE,
                },
                providerKey = &providerKey,
                layerKey = spec.IPv6 ? PInvoke.FWPM_LAYER_ALE_AUTH_CONNECT_V6 : PInvoke.FWPM_LAYER_ALE_AUTH_CONNECT_V4,
                subLayerKey = BootGuardFilters.SubLayerKey,
                numFilterConditions = count,
                filterCondition = count == 0 ? null : conditions,
            };

            filter.weight.type = FWP_DATA_TYPE.FWP_UINT8;
            filter.weight.uint8 = spec.Weight;
            filter.action.type = spec.Role == GuardFilterRole.Block
                ? FWP_ACTION_TYPE.FWP_ACTION_BLOCK
                : FWP_ACTION_TYPE.FWP_ACTION_PERMIT;

            Check(PInvoke.FwpmFilterAdd0(engine, in filter, default), $"add filter '{spec.Name}'");
        }
    }

    /// <summary>Writes the filter's conditions into the buffer and returns how many.</summary>
    private static unsafe uint WriteConditions(GuardFilterSpec spec, FWPM_FILTER_CONDITION0* conditions)
    {
        switch (spec.Role)
        {
            case GuardFilterRole.Loopback:
                conditions[0] = default;
                conditions[0].fieldKey = PInvoke.FWPM_CONDITION_FLAGS;
                conditions[0].matchType = FWP_MATCH_TYPE.FWP_MATCH_FLAGS_ALL_SET;
                conditions[0].conditionValue.type = FWP_DATA_TYPE.FWP_UINT32;
                conditions[0].conditionValue.uint32 = PInvoke.FWP_CONDITION_FLAG_IS_LOOPBACK;
                return 1;

            case GuardFilterRole.Dhcp:
                conditions[0] = default;
                conditions[0].fieldKey = PInvoke.FWPM_CONDITION_IP_PROTOCOL;
                conditions[0].matchType = FWP_MATCH_TYPE.FWP_MATCH_EQUAL;
                conditions[0].conditionValue.type = FWP_DATA_TYPE.FWP_UINT8;
                conditions[0].conditionValue.uint8 = (byte)ProtocolType.Udp;

                conditions[1] = default;
                conditions[1].fieldKey = PInvoke.FWPM_CONDITION_IP_REMOTE_PORT;
                conditions[1].matchType = FWP_MATCH_TYPE.FWP_MATCH_EQUAL;
                conditions[1].conditionValue.type = FWP_DATA_TYPE.FWP_UINT16;
                conditions[1].conditionValue.uint16 = BootGuardFilters.DhcpServerPort(spec.IPv6);
                return 2;

            default:
                return 0;
        }
    }

    private static unsafe bool FilterExists(SafeHandle engine, Guid key)
    {
        uint result = PInvoke.FwpmFilterGetByKey0(engine, in key, out FWPM_FILTER0* filter);

        if (result == unchecked((uint)HRESULT.FWP_E_FILTER_NOT_FOUND.Value))
        {
            return false;
        }

        Check(result, "look up a filter");

        void* memory = filter;
        PInvoke.FwpmFreeMemory0(ref memory);
        return true;
    }

    private static void DeleteFilter(SafeHandle engine, Guid key) =>
        IgnoreNotFound(PInvoke.FwpmFilterDeleteByKey0(engine, in key), HRESULT.FWP_E_FILTER_NOT_FOUND, "delete a filter");

    private static void IgnoreAlreadyExists(uint result, string operation)
    {
        if (result != unchecked((uint)HRESULT.FWP_E_ALREADY_EXISTS.Value))
        {
            Check(result, operation);
        }
    }

    private static void IgnoreNotFound(uint result, HRESULT notFound, string operation)
    {
        if (result != unchecked((uint)notFound.Value))
        {
            Check(result, operation);
        }
    }

    private static void Check(uint result, string operation)
    {
        if (result == 0)
        {
            return;
        }

        // The management API returns plain Win32 codes for RPC-level failures and FWP_E_*
        // HRESULTs for its own; access denied arrives as the former.
        if (result is ErrorAccessDenied or EAccessDenied)
        {
            throw new UnauthorizedAccessException(
                $"Cannot {operation}: this requires running EVBlocker as administrator.");
        }

        throw new InvalidOperationException($"Could not {operation}: WFP error 0x{result:X8}.");
    }

    /// <summary>IANA protocol numbers the conditions need.</summary>
    private enum ProtocolType : byte
    {
        Udp = 17,
    }
}
