using System.Collections;
using System.Runtime.InteropServices;
using Windows.Win32.Foundation;
using Windows.Win32.NetworkManagement.WindowsFirewall;

namespace EVBlocker.Core.Firewall;

/// <summary>
/// <see cref="IFirewallPolicy"/> over the Windows Firewall COM API.
/// </summary>
/// <remarks>
/// The interop is generated by CsWin32 from the official Win32 metadata, not hand-written.
/// INetFwPolicy2 and INetFwRule are dual interfaces, so their vtables start with IUnknown and
/// IDispatch and then run through every property getter and setter in IDL order. Declaring that
/// by hand puts a transcription error one slot away from calling the wrong function, and the
/// write path cannot be exercised without elevation - so the mistake would surface on a user's
/// machine rather than in a test. Generating it moves that correctness onto the metadata.
///
/// It also caught a real error: the CLSID transcribed from memory was wrong.
///
/// Reads work for a standard user. Writes need elevation, and are translated from the COM
/// access-denied HRESULT into <see cref="UnauthorizedAccessException"/> so callers do not have to
/// know COM error codes.
/// </remarks>
public sealed class WindowsFirewallPolicy : IFirewallPolicy
{
    private const int E_ACCESSDENIED = unchecked((int)0x80070005);

    public IReadOnlyList<FirewallRuleSpec> GetRulesInGroup(string group)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(group);

        INetFwRules rules = CreatePolicy().Rules;
        var matches = new List<FirewallRuleSpec>();

        // _NewEnum hands back an IEnumVARIANT; the runtime's COM interop presents that as an
        // IEnumerator, which is why this can be a plain foreach.
        var enumerator = (IEnumerator)rules._NewEnum;

        while (enumerator.MoveNext())
        {
            if (enumerator.Current is not INetFwRule rule)
            {
                continue;
            }

            string? grouping = ReadBstr(rule.Grouping);
            if (!string.Equals(grouping, group, StringComparison.Ordinal))
            {
                continue;
            }

            matches.Add(Read(rule, grouping));
        }

        return matches;
    }

    public void AddRule(FirewallRuleSpec spec)
    {
        ArgumentNullException.ThrowIfNull(spec);

        var rule = (INetFwRule)new NetFwRule();

        WriteBstr(value => rule.Name = value, spec.Name);
        WriteBstr(value => rule.Description = value, spec.Description);
        WriteBstr(value => rule.Grouping = value, spec.Group);
        WriteBstr(value => rule.ApplicationName = value, spec.ApplicationPath);
        WriteBstr(value => rule.ServiceName = value, spec.ServiceName);

        rule.Direction = (NET_FW_RULE_DIRECTION)spec.Direction;
        rule.Action = (NET_FW_ACTION)spec.Action;
        rule.Profiles = (int)spec.Profiles;
        rule.Enabled = spec.Enabled ? VARIANT_BOOL.VARIANT_TRUE : VARIANT_BOOL.VARIANT_FALSE;

        Guard(() => CreatePolicy().Rules.Add(rule), $"add rule '{spec.Name}'");
    }

    public void RemoveRule(string name)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(name);

        Guard(
            () => WriteBstr(value => CreatePolicy().Rules.Remove(value), name),
            $"remove rule '{name}'");
    }

    private static INetFwPolicy2 CreatePolicy() => (INetFwPolicy2)new NetFwPolicy2();

    private static FirewallRuleSpec Read(INetFwRule rule, string? grouping) => new()
    {
        Name = ReadBstr(rule.Name) ?? string.Empty,
        Group = grouping ?? string.Empty,
        Description = ReadBstr(rule.Description),
        ApplicationPath = ReadBstr(rule.ApplicationName),
        ServiceName = ReadBstr(rule.ServiceName),
        Direction = (FirewallDirection)rule.Direction,
        Action = (FirewallAction)rule.Action,
        Profiles = (FirewallProfiles)rule.Profiles,
        Enabled = rule.Enabled == VARIANT_BOOL.VARIANT_TRUE,
    };

    /// <summary>
    /// Reads a BSTR returned by a property getter and frees it.
    /// </summary>
    /// <remarks>
    /// A [propget] BSTR transfers ownership to the caller, so every one of these has to be freed.
    /// Doing it in one place is the only way to be sure none is missed - the leak would be silent
    /// and proportional to how often the rules are listed.
    /// </remarks>
    private static string? ReadBstr(BSTR value)
    {
        IntPtr pointer = value;
        if (pointer == IntPtr.Zero)
        {
            return null;
        }

        try
        {
            return value.ToString();
        }
        finally
        {
            Marshal.FreeBSTR(pointer);
        }
    }

    /// <summary>
    /// Allocates a BSTR, hands it to a property setter, and frees it again.
    /// </summary>
    /// <remarks>
    /// The callee copies the string, so freeing immediately after the call is correct and is what
    /// keeps a setter from leaking one allocation per rule written.
    /// </remarks>
    private static void WriteBstr(Action<BSTR> setter, string? value)
    {
        if (value is null)
        {
            setter(default);
            return;
        }

        IntPtr pointer = Marshal.StringToBSTR(value);
        try
        {
            setter((BSTR)pointer);
        }
        finally
        {
            Marshal.FreeBSTR(pointer);
        }
    }

    /// <summary>
    /// Turns the COM access-denied HRESULT into an exception that says what to do about it.
    /// Everything else is left alone rather than wrapped into something vaguer.
    /// </summary>
    private static void Guard(Action action, string operation)
    {
        try
        {
            action();
        }
        catch (COMException ex) when (ex.HResult == E_ACCESSDENIED)
        {
            throw new UnauthorizedAccessException(
                $"Cannot {operation}: changing Windows Firewall rules requires administrator rights.",
                ex);
        }
    }
}
